version: 2.1

jobs:
  build:
    docker:
      - image: <<parameters.docker_image>>
      - image: circleci/mysql:5.6
        command: mysqld --character-set-server=latin1 --collation-server=latin1_swedish_ci
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
    parameters:
      docker_image:
        type: string
    environment:
      WORKBENCH_DATABASES: '{"default": {"ENGINE": "django.db.backends.mysql", "NAME": "db", "USER": "root", "PASSWORD": "rootpw", "HOST": "127.0.0.1", "OPTIONS": {"charset": "utf8mb4"}}}'
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -U pip wheel
            pip install -r requirements-test.txt
            pip install -r venv/src/xblock-sdk/requirements/base.txt
            pip install -r venv/src/xblock-sdk/requirements/test.txt
            mkdir var
      - save_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run lints
          command: |
            . venv/bin/activate
            pycodestyle eoc_journal --max-line-length=120
            pylint eoc_journal
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python run_tests.py

workflows:
  version: 2
  build:
    jobs:
      - build:
          name: "Ironwood: Python 2.7, Django 1.11"
          docker_image: circleci/python:2.7-browsers
      - build:
          name: "Juniper: Python 3.5, Django 2.2"
          docker_image: circleci/python:3.5-browsers
      - build:
          name: "Koa: Python 3.8, Django 2.2"
          docker_image: circleci/python:3.8-browsers
