version: 2
jobs:
  build-2.7: &test-template
    docker:
      - image: circleci/python:2.7.14-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -U pip wheel
            pip install -r requirements-test.txt
            pip install -r venv/src/xblock-sdk/requirements/base.txt
            pip install -r venv/src/xblock-sdk/requirements/test.txt
            mkdir var
      - save_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pycodestyle eoc_journal --max-line-length=120
            pylint eoc_journal
            python run_tests.py
  build-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5.6-browsers
  build-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.5-browsers
